# Generated by Django 6.0.4 on 2026-04-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('qf_sub_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('qf_access_token', models.TextField(blank=True, null=True)),
                ('qf_refresh_token', models.TextField(blank=True, null=True)),
                ('total_points', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
