# Generated by Django 6.0.4 on 2026-04-10 14:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reflection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ayah_key", models.CharField(max_length=20)),
                ("text_content", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                ("ease_factor", models.FloatField(default=2.5)),
                ("interval", models.IntegerField(default=0)),
                ("repetitions", models.IntegerField(default=0)),
                (
                    "next_review_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("total_points_earned", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reflections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["next_review_date"],
            },
        ),
        migrations.CreateModel(
            name="ReviewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "grade",
                    models.IntegerField(
                        choices=[
                            (0, "Forgot / Complete Failure"),
                            (1, "Hard / Remembered with immense effort"),
                            (2, "Good / Remembered after hesitation"),
                            (3, "Easy / Perfect recall"),
                        ]
                    ),
                ),
                ("points_awarded", models.IntegerField()),
                ("was_in_grace_period", models.BooleanField(default=False)),
                (
                    "reflection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_logs",
                        to="reviews.reflection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at"],
                "indexes": [
                    models.Index(
                        fields=["reviewed_at"], name="reviews_rev_reviewe_11d759_idx"
                    )
                ],
            },
        ),
    ]
