# Generated by Django 6.0.4 on 2026-04-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reflection",
            old_name="text_content",
            new_name="reflection_text",
        ),
    ]
