# Generated by Django 6.0.4 on 2026-04-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_rename_text_content_reflection_reflection_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewlog",
            name="grade",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Forgot / Complete Failure"),
                    (1, "Hard / Remembered with immense effort"),
                    (2, "Good / Remembered after hesitation"),
                    (3, "Easy / Perfect recall"),
                ],
                null=True,
            ),
        ),
    ]
