# Generated by Django 6.0.4 on 2026-04-11 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_reviewlog_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewlog",
            name="reflection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_logs",
                to="reviews.reflection",
            ),
        ),
    ]
